server:
  port: 8080


spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300

logging:
  level:
    com.cooksys: DEBUG

eventBus:
  broker: redis
  redisHost: redis
  redisPort: 6379
  redisTopic: csrt-event-bus

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
