server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
  redis:
    host: redis
    port: 6379

cloud:
  cloud: aws-ec2
  maxNodes: 6
  imageConfig:
    hardwareId: t2.small
    imageId: us-west-2/ami-a9d276c9
    locationId: us-west-2

docker:
  port: 9999

logging:
  level:
     com.cooksys: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
