server:
  port: 8080


spring:
  data:
    elasticsearch:
      cluster-nodes: elasticsearch:9300

  rabbitmq:
    host: rabbitmq
    port: 5672

logging:
  level:
    com.cooksys: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
