info:
  component: Zuul Server

server:
  port: 8764

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eventBus:
  broker: redis
  redisHost: redis
  redisPort: 6379
  redisTopic: csrt-event-bus

logging:
  level:
    com.cooksys.cloud.router: DEBUG
    org.springframework.cloud.netflix.zuul: DEBUG

multipart:
  maxFileSize: 54525952
  maxRequestSize: 54525952


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 3000

eureka:
  instance:
    non-secure-port: 8765
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
