server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672

logging:
  level:
    com.cooksys.csrt.scaler: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
